import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import ScrollReveal from "@/components/ScrollReveal";
import { Button } from "@/components/ui/button";
import { useSEO } from "@/hooks/use-seo";
import { articles } from "@/pages/Insights";
import architecture from "@/assets/editorial-architecture.jpg";

const description = "BitwellForge advises service businesses on the structural constraints governing commercial performance, identifying the interdependencies that impede growth across strategy, acquisition, operations, and digital execution.";
const disciplines = [
  { number: "01", name: "Strategy", title: "Commercial Growth Strategy", detail: "Define the commercial thesis, position the offer, and make every investment answer to a clear market decision.", href: "/services/growth-strategy" },
  { number: "02", name: "Acquisition", title: "Client Acquisition Architecture", detail: "Build deliberate pathways from market attention to qualified conversations, beyond any single channel.", href: "/services/lead-generation" },
  { number: "03", name: "Revenue", title: "High-Ticket Revenue Systems", detail: "Turn the sales process into a repeatable operating discipline with clearer decisions and stronger conversion.", href: "/services/sales-systems" },
  { number: "04", name: "Operations", title: "AI-Powered Revenue Operations", detail: "Connect workflows, data, and automation so the organisation can grow without equivalent friction.", href: "/services/ai-automation" },
];

const Index = () => {
  const reduced = useReducedMotion();
  useSEO({ title: "BitwellForge | Commercial Architecture & Constraint Advisory", description, canonicalPath: "/" });
  return <div className="public-home">
    <section className="public-hero relative flex items-center overflow-hidden section-padding">
      <motion.img src={architecture} alt="Precise geometry of a contemporary institutional building" width={1600} height={900} className="public-hero-image absolute inset-0 h-full w-full" initial={false} animate={reduced ? {} : { scale: 1.04 }} transition={{ duration: 8, ease: "easeOut" }} />
      <div className="public-image-shade absolute inset-0" aria-hidden="true" />
      <div className="relative z-10 mx-auto w-full max-w-[1440px] pt-32 pb-20 md:pt-36 md:pb-28">
        <motion.div initial={reduced ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="max-w-[830px]">
          <p className="public-kicker mb-7">Commercial infrastructure &amp; revenue growth consulting</p>
          <h1 className="font-heading font-semibold leading-[1.08] text-foreground text-[42px] sm:text-[54px] md:text-[65px] lg:text-[78px]">What's assembled breaks down.<br />What's engineered compounds.</h1>
          <div className="mt-8 max-w-[640px] border-l-2 border-accent pl-5 md:mt-10 md:pl-7"><p className="text-[16px] leading-[1.7] text-muted-foreground md:text-[18px]">{description}</p></div>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row sm:items-center md:mt-11">
            <Button asChild className="h-12 rounded-none px-7 text-[13px] sm:h-14"><Link to="/contact?service=General+Inquiry">Book Infrastructure Audit <ArrowRight size={16} /></Link></Button>
            <Button asChild variant="outline" className="h-12 rounded-none border-foreground bg-background/70 px-7 text-[13px] sm:h-14"><Link to="/about">Explore the firm <ArrowUpRight size={16} /></Link></Button>
          </div>
        </motion.div>
      </div>
      <div className="absolute bottom-0 left-0 right-0 z-10 hidden border-t border-border bg-background/80 md:block"><div className="section-padding mx-auto flex max-w-[1440px] items-center justify-between py-4 text-[11px] font-medium uppercase tracking-wide text-muted-foreground"><span>Independent advisory</span><span>Strategy / Acquisition / Revenue / Operations</span><span>Worldwide</span></div></div>
    </section>

    <section className="section-padding border-t border-border bg-background py-20 md:py-28" id="expertise"><div className="mx-auto max-w-[1440px]">
      <ScrollReveal><div className="grid gap-8 border-b border-border pb-12 lg:grid-cols-12 lg:gap-16"><div className="lg:col-span-7"><p className="public-kicker mb-5">Our expertise / 01</p><h2 className="max-w-[760px] font-heading text-[36px] font-semibold leading-[1.14] text-foreground md:text-[50px]">Four disciplines.<br />One revenue infrastructure.</h2></div><p className="max-w-[390px] self-end text-[16px] leading-[1.7] text-muted-foreground lg:col-span-5">The commercial system is only as strong as the relationship between its parts. Our work addresses those relationships rather than isolated symptoms.</p></div></ScrollReveal>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4">{disciplines.map((item, i) => <ScrollReveal key={item.number} delay={i * 100} className="h-full"><article className="group flex h-full min-h-[360px] flex-col border-b border-border py-9 md:border-r md:px-6 lg:min-h-[420px] lg:px-7 first:pl-0 last:border-r-0"><div className="flex items-center justify-between text-[12px] font-semibold text-accent"><span>{item.number} / {item.name}</span><ArrowUpRight size={18} className="transition-transform duration-300 group-hover:translate-x-1 group-hover:-translate-y-1" /></div><div className="mt-14"><h3 className="font-heading text-[27px] font-semibold leading-[1.18] text-foreground md:text-[30px]">{item.title}</h3><p className="mt-6 text-[14px] leading-[1.7] text-muted-foreground">{item.detail}</p></div><Link className="mt-auto inline-flex min-h-11 items-center gap-2 pt-7 text-[12px] font-semibold text-accent hover:underline" to={item.href}>Explore discipline <ArrowRight size={15} /></Link></article></ScrollReveal>)}</div>
      <div className="flex justify-end pt-8"><Link className="inline-flex min-h-11 items-center gap-2 text-[13px] font-semibold text-accent hover:underline" to="/services">View all services <ArrowRight size={16} /></Link></div>
    </div></section>

    <section className="public-deep section-padding py-20 md:py-28"><div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-12 lg:gap-20"><ScrollReveal className="lg:col-span-5"><p className="public-kicker mb-6">Our approach / 02</p><h2 className="font-heading text-[35px] font-semibold leading-[1.16] text-foreground md:text-[48px]">Find the constraint.<br />Design the system.</h2><p className="mt-7 max-w-[430px] text-[16px] leading-[1.75] text-muted-foreground">A visible performance issue is rarely a standalone problem. We study how strategy, demand, conversion, and delivery interact before deciding what to change.</p><Link to="/process" className="mt-9 inline-flex min-h-11 items-center gap-3 border-b border-border text-[13px] font-semibold text-foreground hover:text-accent">How we work <ArrowUpRight size={17} /></Link></ScrollReveal><ScrollReveal className="lg:col-span-7" delay={120}><div className="border-t border-border"><div className="grid grid-cols-[70px_1fr] gap-5 border-b border-border py-6 sm:grid-cols-[110px_1fr_1fr]"><span className="text-[12px] font-semibold text-accent">INPUT</span><span className="font-heading text-[22px] text-foreground">Commercial signal</span><span className="col-start-2 text-[13px] text-muted-foreground sm:col-auto">What the business observes</span></div><div className="grid grid-cols-[70px_1fr] gap-5 border-b border-border py-6 sm:grid-cols-[110px_1fr_1fr]"><span className="text-[12px] font-semibold text-accent">ANALYSIS</span><span className="font-heading text-[22px] text-foreground">Underlying constraint</span><span className="col-start-2 text-[13px] text-muted-foreground sm:col-auto">Why performance stalls</span></div><div className="grid grid-cols-[70px_1fr] gap-5 border-b border-border py-6 sm:grid-cols-[110px_1fr_1fr]"><span className="text-[12px] font-semibold text-accent">DESIGN</span><span className="font-heading text-[22px] text-foreground">Connected intervention</span><span className="col-start-2 text-[13px] text-muted-foreground sm:col-auto">What the system needs</span></div><div className="grid grid-cols-[70px_1fr] gap-5 py-6 sm:grid-cols-[110px_1fr_1fr]"><span className="text-[12px] font-semibold text-accent">OUTCOME</span><span className="font-heading text-[22px] text-foreground">Durable capacity</span><span className="col-start-2 text-[13px] text-muted-foreground sm:col-auto">What continues to work</span></div></div></ScrollReveal></div></section>

    <section className="section-padding bg-secondary py-20 md:py-28"><div className="mx-auto max-w-[1440px]"><ScrollReveal><div className="mb-12 flex flex-col justify-between gap-6 border-b border-border pb-9 md:flex-row md:items-end"><div><p className="public-kicker mb-5">Perspectives / 03</p><h2 className="font-heading text-[36px] font-semibold text-foreground md:text-[50px]">Latest insights</h2></div><Link to="/insights" className="inline-flex min-h-11 items-center gap-3 text-[13px] font-semibold text-accent hover:underline">Explore all insights <ArrowRight size={16} /></Link></div></ScrollReveal><div className="grid gap-0 md:grid-cols-2 lg:grid-cols-3">{articles.slice(0, 3).map((article, i) => <ScrollReveal key={article.slug} delay={i * 100} className="h-full"><Link to={`/insights/${article.slug}`} className="group flex h-full min-h-[335px] flex-col border-b border-border bg-background p-7 transition-colors duration-300 hover:bg-card md:border-r md:p-9 last:border-r-0"><span className="public-kicker">{article.category} / {article.date}</span><h3 className="mt-9 font-heading text-[27px] font-semibold leading-[1.2] text-foreground group-hover:underline md:text-[30px]">{article.title}</h3><p className="mt-5 line-clamp-3 text-[14px] leading-[1.7] text-muted-foreground">{article.excerpt}</p><span className="mt-auto flex min-h-11 items-end gap-2 pt-8 text-[12px] font-semibold text-accent">Read perspective <ArrowUpRight size={16} className="transition-transform duration-300 group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link></ScrollReveal>)}</div></div></section>

    <section className="section-padding bg-background py-20 md:py-28"><div className="mx-auto grid max-w-[1440px] gap-12 border-t border-border pt-12 lg:grid-cols-12 lg:gap-20"><ScrollReveal className="lg:col-span-6"><p className="public-kicker mb-5">Global footprint / 04</p><h2 className="font-heading text-[35px] font-semibold leading-[1.18] text-foreground md:text-[48px]">Built for businesses without borders.</h2></ScrollReveal><ScrollReveal className="lg:col-span-6" delay={100}><p className="max-w-[540px] text-[16px] leading-[1.8] text-muted-foreground">BitwellForge works with service businesses across markets. Our engagements are designed for remote collaboration, with a focus on commercial context rather than geography.</p><div className="mt-9 grid grid-cols-2 border-y border-border py-6 text-[12px] font-semibold uppercase text-accent"><span>Operating model</span><span>Worldwide / Remote</span></div></ScrollReveal></div></section>
    <section className="public-deep section-padding py-20 md:py-28"><div className="mx-auto flex max-w-[1440px] flex-col items-start justify-between gap-9 md:flex-row md:items-end"><div><p className="public-kicker mb-6">Start a conversation</p><h2 className="max-w-[720px] font-heading text-[38px] font-semibold leading-[1.12] text-foreground md:text-[56px]">Build the infrastructure behind what comes next.</h2></div><Button asChild className="h-14 shrink-0 rounded-none bg-background px-7 text-[13px] text-primary hover:bg-secondary"><Link to="/contact?service=General+Inquiry">Book Infrastructure Audit <ArrowRight size={16} /></Link></Button></div></section>
  </div>;
};
export default Index;
